language: node_js
node_js:
- 5.0
script: ./ci/travis_deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "hdfghsfghsdfg4esgh"
  - COMMIT_AUTHOR_EMAIL: "tf@molch.at"
cache:
  directories:
    - node_modules
